// generated by Fast Light User Interface Designer (fluid) version 1.0108

#include "gui.h"

void GUI::cb_DBG_i(Fl_Button*, void*) {
  DBG_cb();
}
void GUI::cb_DBG(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_DBG_i(o,v);
}

void GUI::cb_Render_i(Fl_Button*, void*) {
  SetLightPos();
}
void GUI::cb_Render(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Render_i(o,v);
}

void GUI::cb_X_i(Fl_Button*, void*) {
  LightPosX();
}
void GUI::cb_X(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_X_i(o,v);
}

void GUI::cb_X1_i(Fl_Button*, void*) {
  LightNegX();
}
void GUI::cb_X1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_X1_i(o,v);
}

void GUI::cb_Y_i(Fl_Button*, void*) {
  LightPosY();
}
void GUI::cb_Y(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Y_i(o,v);
}

void GUI::cb_Y1_i(Fl_Button*, void*) {
  LightNegY();
}
void GUI::cb_Y1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Y1_i(o,v);
}

void GUI::cb_Z_i(Fl_Button*, void*) {
  LightPosZ();
}
void GUI::cb_Z(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Z_i(o,v);
}

void GUI::cb_Z1_i(Fl_Button*, void*) {
  LightNegZ();
}
void GUI::cb_Z1(Fl_Button* o, void* v) {
  ((GUI*)(o->parent()->user_data()))->cb_Z1_i(o,v);
}
#include "scene.h"

GUI::GUI() {
  { uiw = new Fl_Double_Window(373, 312, "Evan\'s Photometric Stereo");
    uiw->user_data((void*)(this));
    { Fl_Button* o = new Fl_Button(70, 20, 230, 40, "DBG");
      o->selection_color(FL_DARK_RED);
      o->callback((Fl_Callback*)cb_DBG);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(70, 245, 230, 40, "Render");
      o->callback((Fl_Callback*)cb_Render);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(70, 146, 65, 40, "X++");
      o->callback((Fl_Callback*)cb_X);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(70, 190, 65, 40, "X--");
      o->callback((Fl_Callback*)cb_X1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(155, 145, 65, 40, "Y++");
      o->callback((Fl_Callback*)cb_Y);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(155, 190, 65, 40, "Y--");
      o->callback((Fl_Callback*)cb_Y1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(235, 145, 65, 40, "Z++");
      o->callback((Fl_Callback*)cb_Z);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(235, 195, 65, 40, "Z--");
      o->callback((Fl_Callback*)cb_Z1);
    } // Fl_Button* o
    { lPosDisp = new Fl_Text_Display(100, 95, 165, 40, "Current Light Position");
    } // Fl_Text_Display* lPosDisp
    uiw->end();
  } // Fl_Double_Window* uiw
}

int main(int argc, char **argv) {
  scene = new Scene;
  return Fl::run();
}

void GUI::show() {
  uiw->show();

}

void GUI::DBG_cb() {
  scene->DBG();
}

void GUI::LightPosX() {
  scene->lightPosX();
  
}

void GUI::LightNegX() {
  scene->lightNegX();
}

void GUI::LightPosY() {
  scene->lightPosY();
}

void GUI::LightNegY() {
  scene->lightNegY();
}

void GUI::LightPosZ() {
  scene->lightPosZ();
}

void GUI::LightNegZ() {
  scene->lightNegZ();
}

void GUI::SetLightPos() {
  scene->setLightPos();
}
