// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
  void cb_Render_i(Fl_Button*, void*);
  static void cb_Render(Fl_Button*, void*);
  void cb_X_i(Fl_Button*, void*);
  static void cb_X(Fl_Button*, void*);
  void cb_X1_i(Fl_Button*, void*);
  static void cb_X1(Fl_Button*, void*);
  void cb_Y_i(Fl_Button*, void*);
  static void cb_Y(Fl_Button*, void*);
  void cb_Y1_i(Fl_Button*, void*);
  static void cb_Y1(Fl_Button*, void*);
  void cb_Z_i(Fl_Button*, void*);
  static void cb_Z(Fl_Button*, void*);
  void cb_Z1_i(Fl_Button*, void*);
  static void cb_Z1(Fl_Button*, void*);
public:
  Fl_Text_Display *lPosDisp;
private:
  void cb_Render1_i(Fl_Button*, void*);
  static void cb_Render1(Fl_Button*, void*);
  void cb_Render2_i(Fl_Button*, void*);
  static void cb_Render2(Fl_Button*, void*);
public:
  void show();
  void DBG_cb();
  void LightPosX();
  void LightNegX();
  void LightPosY();
  void LightNegY();
  void LightPosZ();
  void LightNegZ();
  void SetLightPos();
  void SetLightPosFive();
  void SetLightPosSpec();
};
#endif
