// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>

class GUI {
public:
  GUI();
  Fl_Double_Window *uiw;
private:
  void cb_DBG_i(Fl_Button*, void*);
  static void cb_DBG(Fl_Button*, void*);
  void cb_Save_i(Fl_Button*, void*);
  static void cb_Save(Fl_Button*, void*);
  void cb_Load_i(Fl_Button*, void*);
  static void cb_Load(Fl_Button*, void*);
  void cb_Go_i(Fl_Button*, void*);
  static void cb_Go(Fl_Button*, void*);
  void cb_Save1_i(Fl_Button*, void*);
  static void cb_Save1(Fl_Button*, void*);
  void cb_Load1_i(Fl_Button*, void*);
  static void cb_Load1(Fl_Button*, void*);
  void cb_Go1_i(Fl_Button*, void*);
  static void cb_Go1(Fl_Button*, void*);
  void cb_Save2_i(Fl_Button*, void*);
  static void cb_Save2(Fl_Button*, void*);
  void cb_Load2_i(Fl_Button*, void*);
  static void cb_Load2(Fl_Button*, void*);
  void cb_Go2_i(Fl_Button*, void*);
  static void cb_Go2(Fl_Button*, void*);
public:
  void show();
  void DBG_cb();
  void SaveView0B_cb();
  void LoadView0B_cb();
  void GoToView0B_cb();
  void SaveView1B_cb();
  void LoadView1B_cb();
  void GoToView1B_cb();
  void SaveView2B_cb();
  void LoadView2B_cb();
  void GoToView2B_cb();
};
#endif
